#!/bin/bash
######################################################################
#  Mastering the Raspberry Pi, ISBN13: 978-1-484201-82-4
#  Warren W. Gay VE3WWG
######################################################################

GPIO="$1"
SYS=/sys/class/gpio
DEV=/sys/class/gpio/gpio$GPIO

if [ ! -d $DEV ] ; then
	# Make pin visible
	echo $GPIO >$SYS/export	
fi

# Set pin to output
echo out >$DEV/direction

function put() {
	# Set value of pin (1 or 0)
	echo $1 >$DEV/value
}

# Main loop:
while true ; do
	put 1
	echo "GPIO $GPIO: on"
	#sleep 1
	put 0
	echo "GPIO $GPIO: off  $(date)"
	#sleep 1
done

######################################################################
#  End gp.  Public Domain license.
######################################################################
