#!/bin/bash

######################################################################
#       LED_Blink_Bash
#
# This program get gpio number as input and then blink the LED that
# connected to it
######################################################################

GPIO="$1"
SYS=/sys/class/gpio
DEV=/sys/class/gpio/gpio$GPIO

if [ ! -d $DEV ] ; then
	echo $GPIO >$SYS/export	
fi

# Set pin to output
echo out >$DEV/direction

function SetValue()
{
	# Set value of pin (1 or 0)
	echo $1 >$DEV/value
}

# Main loop:
while true ; do
	SetValue 1
	echo "GPIO $GPIO: on"
	sleep 1
	SetValue 0
	echo "GPIO $GPIO: off  $(date)"
	sleep 1
done
