#!/bin/bash

set -eu

sudo gpio -g mode 18 pwm
var=0
max=1023
min=0
inc=1
while true ; do
        sudo gpio -g pwm 18 $var
        echo "pwm : $var"
        #sleep 0.1
	let var=var+inc
	if [ $var -eq $max ] ; then
		let inc=-1
	fi	

	if [ $var -eq $min ] ; then
		let inc=1
	fi
done

